name: BankNotes
main: AndreasHGK\BankNotes\Main
version: 1.1.0
api: [3.0.0]
load: POSTWORLD
author: AndreasHGK
description: A plugin that makes money into an item to trade with!
softdepend: ["EconomyAPI"]

commands:
 note:
  description: "Withdraw money and put it on a bank note"
  usage: "/note {amount}"
  permission: banknotes.get
  aliases: ["withdraw"]
 banknotes:
  description: "plugin commands"
  usage: "/banknotes <subcommand>"
  permission: banknotes.command
 deposit:
  description: "Deposit a note to your account"
  usage: "/deposit"
  permission: banknotes.deposit

permissions:
 banknotes:
  default: true
  description: "bankNotes root permission (useless)"
  children:
   banknotes.get:
    default: true
    description: "allow players to withdraw banknotes"
   banknotes.deposit:
    default: true
    description: "allow players to deposit banknotes"
   banknotes.command:
    default: true
    description: "plugin commands"
